### PR TITLE
[WIP] ZF3 components compatibility

### PR DESCRIPTION
**Pull request by AGmakonts**
I've started to modernize all modules required by Apigility to support newer versions of ZF components.
oauth 2 is another one in the series.

This one is still a WIP because I had problems with fixing data provider errors in tests.

```
1) Warning
The data provider specified for ZFTest\OAuth2\Adapter\Pdo\AccessTokenTest::testSetAccessToken is invalid.
Could not find a valid ServiceManager for RoutePluginManager

2) Warning
The data provider specified for ZFTest\OAuth2\Adapter\Pdo\AuthorizationCodeTest::testGetAuthorizationCode is invalid.
Could not find a valid ServiceManager for RoutePluginManager

3) Warning
The data provider specified for ZFTest\OAuth2\Adapter\Pdo\AuthorizationCodeTest::testSetAuthorizationCode is invalid.
Could not find a valid ServiceManager for RoutePluginManager

4) Warning
The data provider specified for ZFTest\OAuth2\Adapter\Pdo\AuthorizationCodeTest::testExpireAccessToken is invalid.
Could not find a valid ServiceManager for RoutePluginManager

5) Warning
The data provider specified for ZFTest\OAuth2\Adapter\Pdo\ClientCredentialsTest::testCheckClientCredentials is invalid.
Could not find a valid ServiceManager for RoutePluginManager

6) Warning
The data provider specified for ZFTest\OAuth2\Adapter\Pdo\ClientTest::testGetClientDetails is invalid.
Could not find a valid ServiceManager for RoutePluginManager

7) Warning
The data provider specified for ZFTest\OAuth2\Adapter\Pdo\ClientTest::testCheckRestrictedGrantType is invalid.
Could not find a valid ServiceManager for RoutePluginManager

8) Warning
The data provider specified for ZFTest\OAuth2\Adapter\Pdo\ClientTest::testGetAccessToken is invalid.
Could not find a valid ServiceManager for RoutePluginManager

9) Warning
The data provider specified for ZFTest\OAuth2\Adapter\Pdo\ClientTest::testSaveClient is invalid.
Could not find a valid ServiceManager for RoutePluginManager

10) Warning
The data provider specified for ZFTest\OAuth2\Adapter\Pdo\ClientTest::testIsPublicClient is invalid.
Could not find a valid ServiceManager for RoutePluginManager

11) Warning
The data provider specified for ZFTest\OAuth2\Adapter\Pdo\ClientTest::testGetClientScope is invalid.
Could not find a valid ServiceManager for RoutePluginManager

12) Warning
The data provider specified for ZFTest\OAuth2\Adapter\Pdo\JwtAccessTokenTest::testJwtWithJti is invalid.
Could not find a valid ServiceManager for RoutePluginManager

13) Warning
The data provider specified for ZFTest\OAuth2\Adapter\Pdo\JwtBearerTest::testGetClientKey is invalid.
Could not find a valid ServiceManager for RoutePluginManager

14) Warning
The data provider specified for ZFTest\OAuth2\Adapter\Pdo\PublicKeyTest::testSetAccessToken is invalid.
Could not find a valid ServiceManager for RoutePluginManager

15) Warning
The data provider specified for ZFTest\OAuth2\Adapter\Pdo\RefreshTokenTest::testSetRefreshToken is invalid.
Could not find a valid ServiceManager for RoutePluginManager

16) Warning
The data provider specified for ZFTest\OAuth2\Adapter\Pdo\ScopeTest::testScopeExists is invalid.
Could not find a valid ServiceManager for RoutePluginManager

17) Warning
The data provider specified for ZFTest\OAuth2\Adapter\Pdo\ScopeTest::testGetDefaultScope is invalid.
Could not find a valid ServiceManager for RoutePluginManager

18) Warning
The data provider specified for ZFTest\OAuth2\Adapter\Pdo\UserCredentialsTest::testCheckUserCredentials is invalid.
Could not find a valid ServiceManager for RoutePluginManager

19) Warning
The data provider specified for ZFTest\OAuth2\Adapter\Pdo\UserCredentialsTest::testUserClaims is invalid.
Could not find a valid ServiceManager for RoutePluginManager
```

### CODE REVIEW

**Comment by AGmakonts** [comment]
@MichaelGooden will do, I'll clean up all PRs for apigility this week.

**Comment by DannyvdSluijs** [comment]
@AGmakonts I was looking into using using zf-rest with zf3. Anything you need help or support on ?

**Comment by weierophinney** [comment]
@AGmakonts I've pulled locally and resolved the conflicts; I can take it from here. Thanks!

**Comment by weierophinney** [comment]
Merged to develop with #148, for release with 1.4.0.

**Pull request closed without merging**
